# Generated by Django 5.1.6 on 2025-02-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_number',
        ),
    ]
