# Generated by Django 5.1.6 on 2025-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0005_remove_customuser_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='project_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(blank=True, choices=[('სტარტაპ კონსულტაცია/Startup Consultation', 'სტარტაპ კონსულტაცია/Startup Consultation'), ('საგრანტო კონსულტაცია/Grant Consultation', 'საგრანტო კონსულტაცია/Grant Consultation'), ('საინჟინრო კონსულტაცია/Engineering consultation', 'საინჟინრო კონსულტაცია/Engineering consultation'), ('პროგრამული კონსულტაცია/Software consultation', 'პროგრამული კონსულტაცია/Software consultation'), ('იდეის დამუშავება/Working on the idea', 'იდეის დამუშავება/Working on the idea'), ('3D პრინტერის პროექტზე კონსულტაცია/Consultation for 3D printer project', '3D პრინტერის პროექტზე კონსულტაცია/Consultation for 3D printer project'), ('ლაზერული მჭრელის პროექტზე კონსულტაცია/Consultation for laser cutter machine project', 'ლაზერული მჭრელის პროექტზე კონსულტაცია/Consultation for laser cutter machine project'), ('CNC პროგრამირებადი ჩარხის პროექტზე კონსულტაცია/Consultation for CNC machine project', 'CNC პროგრამირებადი ჩარხის პროექტზე კონსულტაცია/Consultation for CNC machine project'), ('სხვა/other', 'სხვა/other')], max_length=255, null=True),
        ),
    ]
