# Generated by Django 5.1.6 on 2025-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0006_booking_meeting_type_booking_project_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='project_goal',
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
