# Generated by Django 5.1.6 on 2025-02-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0007_remove_booking_project_goal_booking_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deactivated',
            field=models.BooleanField(default=False, verbose_name='Deactivate Account'),
        ),
    ]
