# Generated by Django 5.1.6 on 2025-02-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0008_customuser_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='report_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
