# Generated by Django 5.1.6 on 2025-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0009_booking_report_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
