# Generated by Django 5.1.6 on 2025-02-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0010_booking_final_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='final_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='report_reminder_sent',
        ),
    ]
