# Generated by Django 5.1.6 on 2025-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0011_remove_booking_final_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
