# Generated by Django 5.1.6 on 2025-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0012_booking_final_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
