# Generated by Django 5.1.6 on 2025-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0013_booking_google_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='booking_limit',
            field=models.IntegerField(default=3, verbose_name='Remaining Bookings'),
        ),
    ]
